channels:
  - defaults
  - vfonov
dependencies:
  - r-codetools
  - libxml2
  - udunits2
  - binutils_linux-64
  - r-knitr
  - r-lwgeom
  - r-uuid
  - r-markdown
  - gxx_linux-64
  - r-gtable
  - r-lattice
  - libcurl
  - tktable
  - r-svglite
  - beautifulsoup4
  - r-sp
  - requests
  - r-blob
  - r-forcats
  - libxcb
  - gxx_impl_linux-64
  - r-jsonlite
  - r-stringr
  - r-ellipsis
  - r-promises
  - r-webshot
  - r-reshape2
  - r-pkgconfig
  - libffi
  - json-c
  - r-dichromat
  - r-lubridate
  - krb5
  - r-munsell
  - make
  - fontconfig
  - r-cli
  - libdap4
  - r-jpeg
  - r-mass
  - r-class
  - r-rstudioapi
  - libkml
  - r-brew
  - r-pillar
  - r-boot
  - r-glue
  - r-scales
  - libspatialite
  - geos
  - poppler
  - expat
  - libstdcxx-ng
  - xerces-c
  - freexl
  - r-e1071
  - r-tibble
  - r-xfun
  - r-callr
  - r-base
  - pandoc
  - r-htmlwidgets
  - r-sourcetools
  - r-colorspace
  - libgfortran-ng
  - r-utf8
  - r-hms
  - r-digest
  - freetype
  - gfortran_impl_linux-64
  - libpq
  - jpeg
  - ca-certificates
  - jq
  - chardet
  - r-rjson
  - xz
  - r-curl
  - setuptools
  - libpng
  - r-assertthat
  - urllib3
  - asn1crypto
  - python=3.6
  - r-haven
  - gcc_impl_linux-64
  - r-processx
  - r-png
  - r-udunits2
  - _r-mutex
  - r-cluster
  - r-gridextra
  - r-bitops
  - r-rsqlite
  - soupsieve
  - openjpeg
  - curl
  - r-rcolorbrewer
  - r-r6
  - openjdk
  - r-evaluate
  - r-tidyselect
  - r-kernsmooth
  - libnetcdf
  - r-memoise
  - r-modelr
  - r-rematch
  - r-osmdata
  - sqlite
  - r-rgooglemaps
  - pysocks
  - r-dbi
  - r-classint
  - libedit
  - libgdal
  - r-crosstalk
  - fribidi
  - r-leaflet
  - r-openstreetmap
  - r-yaml
  - r
  - r-clipr
  - readline
  - r-fs
  - r-broom
  - r-ps
  - r-rlang
  - icu
  - r-backports
  - r-xml2
  - _libgcc_mutex
  - r-withr
  - libboost
  - pyopenssl
  - cffi
  - r-shiny
  - r-tidyr
  - glib
  - pixman
  - r-later
  - r-bit64
  - r-xtable
  - r-openssl
  - zlib
  - r-sf
  - cryptography
  - r-base64enc
  - r-ggmap
  - harfbuzz
  - r-readxl
  - r-httpuv
  - pcre
  - r-lme4
  - r-nlme
  - r-whisker
  - certifi
  - r-dplyr
  - six
  - r-progress
  - r-spatial
  - gfortran_linux-64
  - r-matrix
  - r-mime
  - libtiff
  - bzip2
  - r-htmltools
  - r-httr
  - r-purrr
  - graphite2
  - r-raster
  - r-crayon
  - libssh2
  - r-rapidjsonr
  - r-viridislite
  - r-plyr
  - bwidget
  - r-stringi
  - r-minqa
  - r-rcpp
  - hdf5
  - r-rgeos
  - r-askpass
  - r-ggplot2
  - r-mgcv
  - gcc_linux-64
  - giflib
  - poppler-data
  - r-reprex
  - r-sys
  - r-gdtools
  - ncurses
  - idna
  - cairo
  - pango
  - r-recommended
  - r-lazyeval
  - r-generics
  - openssl
  - r-xml
  - r-readr
  - r-tmap
  - r-fansi
  - r-magrittr
  - r-units
  - wheel
  - r-rpart
  - r-nloptr
  - tk
  - r-prettyunits
  - pip
  - r-labeling
  - zstd
  - r-rjava
  - r-cellranger
  - r-viridis
  - kealib
  - r-rmarkdown
  - r-rgdal
  - libgcc-ng
  - r-foreign
  - r-highr
  - r-tidyverse
  - pycparser
  - oniguruma
  - libuuid
  - gmp
  - r-mapview
  - r-rvest
  - r-tmaptools
  - binutils_impl_linux-64
  - hdf4
  - r-dbplyr
  - r-tinytex
  - r-selectr
  - proj4
  - r-jsonify
  - r-nnet
  - r-bit
  - r-geojsonsf
  - r-bh
  - r-rcppeigen
  - r-survival
  - r-plogr
  - r-satellite
  - r-survminer
  - r-hexbin
  - r-flexdashboard
